### ISSUE TITLE
Allow blacklisting files

### ISSUE THREAD

**Issue by vmsp** [kezabelle/django-shouty-templates#6]
Currently, we can ignore a specific variable in all files:

``` python
SHOUTY_VARIABLE_BLACKLIST = {
    "chef.can_add_cakes": ("*",)
}
```

It would be great if we could also ignore all missing variables for a certain file:

``` python
SHOUTY_VARIABLE_BLACKLIST = {
    "*": ("third_party_app/template.html",)
}
```

As shown, this is useful for telling shouty-templates to ignore third party apps that, short of sending a patch upstream, I can do nothing about.

**Comment by kezabelle** [comment]
Hi! thanks for your interest in this package, and for the feedback.

It probably isn't something _I'd_ use, because I'd just do:
```
SHOUTY_VARIABLE_BLACKLIST = {
    "title": ("third_party_app/template.html",),
    "subtitle": ("third_party_app/template.html",),
    # etc
}
```
so that any time I upgrade the 3rd party package, any changes to which variables are provided/used is highlighted.

**But!** I'm also fully aware that it's kind of painful to discover all the individual variables which might be laxly set (see: the builtin list of variables, to allow Django itself to work!) and I've taken a first shot at it - if you try master as of 147bddc888b10285a78138d16410b80f2c2d6f9a I'll either have broken everything horribly (despite tests!) or hopefully allowed for silencing a whole template (or series of).

**Comment by vmsp** [comment]
Thanks for the quick response!

I've been doing just that with a somewhat large Django project and ended up adding quite a lot of entries, hence my request.

I'll let you know how things go as soon as I can try out the patch.

**Comment by vmsp** [comment]
Hi! Finally had time to test the feature. I might have found a bug, or I might be misunderstanding how shouty works.

I get this:

```
Variable 'html5_required' in template '<unknown source>' does not resolve.
You may silence this globally by adding 'html5_required' to the settings.SHOUTY_VARIABLE_BLACKLIST iterable.
You may silence this occurance only by adding one of 'bootstrap4/field.html', 'bootstrap4/uni_form.html' to the 'html5_required' key to the settings.SHOUTY_VARIABLE_BLACKLIST iterable.
```

In settings I added:

```python
SHOUTY_VARIABLE_BLACKLIST = {
    '*': [
        'bootstrap4/uni_form.html',
        'bootstrap4/field.html',
    ],
}
```

But the warning persists. If I also include `<unknown source>` everything works as (I) intended. If I explicitly add the missing variable `'html5_required': ['bootstrap4/field.html']` it also works.

**Comment by kezabelle** [comment]
>  I might have found a bug, or I might be misunderstanding how shouty works.

I don't think you're misunderstanding, it's far more likely to be rife with issues :)

> Variable 'html5_required' in template '<unknown source>' does not resolve.

`<unknown source>` is basically "couldn't find the template by walking backwards through the context" which is kinda fraught with potential false positives & negatives because Django is unfortunately bad at figuring out where a template error occurred (see [Django ticket 28935](https://code.djangoproject.com/ticket/28935) and [27956](https://code.djangoproject.com/ticket/27956)) ... the chance of it causing problems also unfortunately rises with custom template tags and 3rd party libs ... and I *think* your use case is both, because that looks like a series of crispy-forms templates, maybe?

> In settings I added [... the templates ...] but the warning persists.

That's certainly interesting and counter to the intent.

If it is crispy forms, let me know and I'll try and find time to further delve into the problem, without the promise of success because IIRC they use all kinds of fun template tag jiggery-pokery.

**Comment by kezabelle** [comment]
Well. I have an inkling of where the problem lies, and why you have to ignore `<unknown source>` specifically, instead of the templates you might expect the problem to occur in. `html5_required` **never appears** in **any template**:

```
/path/python3.7/site-packages/crispy_forms/templatetags/crispy_forms_field.py:        self.html5_required = "html5_required"
/path/python3.7/site-packages/crispy_forms/templatetags/crispy_forms_field.py:                template.Variable(self.html5_required),
/path/python3.7/site-packages/crispy_forms/templatetags/crispy_forms_field.py:        field, attrs, html5_required = context.render_context[self]
/path/python3.7/site-packages/crispy_forms/templatetags/crispy_forms_field.py:            html5_required = html5_required.resolve(context)
/path/python3.7/site-packages/crispy_forms/templatetags/crispy_forms_field.py:            html5_required = False
/path/python3.7/site-packages/crispy_forms/templatetags/crispy_forms_field.py:            if html5_required and field.field.required and "required" not in widget.attrs:
/path/python3.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py:            "html5_required": attrs.get("html5_required", False),
/path/python3.7/site-packages/crispy_forms/tests/test_form_helper.py:def test_html5_required():
/path/python3.7/site-packages/crispy_forms/tests/test_form_helper.py:    form.helper.html5_required = True
/path/python3.7/site-packages/crispy_forms/tests/test_form_helper.py:    form.helper.html5_required = False
/path/python3.7/site-packages/crispy_forms/helper.py:    html5_required = False
/path/python3.7/site-packages/crispy_forms/helper.py:            "html5_required": self.html5_required,
```
and it's actually set up in ``crispy_forms_field.py`` here:
```
[...]
 82  	            context.render_context[self] = (
 83  	                template.Variable(self.field),
 84  	                self.attrs,
 85 ->	                template.Variable(self.html5_required),
 86  	            )
 87
[...]
 90  	        try:
 91  ->	            html5_required = html5_required.resolve(context)
 92  	        except template.VariableDoesNotExist:
 93  	            html5_required = False
[...]
```

Not entirely sure what to do about that right now. Need to ponder what I *can* even do.

**Comment by kezabelle** [comment]
Alrighty, I've made a bunch more changes. Perhaps now I've got the logic correct. There's now 2 test cases covering crispy forms specifically and `*`, one of which declares:
```
SHOUTY_VARIABLE_BLACKLIST={
                    "*": [
                        "bootstrap4/uni_form.html",
                        "bootstrap4/field.html",
                        "bootstrap4/layout/help_text_and_errors.html",
                    ]
                }
```
(notably doesn't include `<unknown source>` and should *not* raise for `html5_required` now)
and another with:
```
SHOUTY_VARIABLE_BLACKLIST={
                    "*": [
                        "bootstrap4/uni_form.html",
                        "bootstrap4/field.html",
                        "bootstrap4/layout/help_text_and_errors.html",
                    ],
                    "html5_required": ["bootstrap4/field.html"],
                }
```
which was previously -- as you noted -- not behaving the same, but *should've* been, and similarly should not raise.

Give it a spin when you're able and let me know if it's still broken/more broken/less broken ... one can only hope for the latter :)

**Comment by vmsp** [comment]
Sorry, once again, for taking so long, @kezabelle!

The files are indeed django-crispy-forms templates, as you rightly assumed. I just pulled from master and the issues seem to be solved. Thank you!

I plan to keep using the library - from master, now that I'm on it - so count on me to do some real-world testing. Hopefully, I'll also add shouty-orm to the project I'm working on after I'm done with it.
