### ISSUE TITLE
How to ignore an unknown variable explicitly?

### ISSUE THREAD

**Issue by guettli** [kezabelle/django-shouty-templates#8]
```

{{ missing_var }}

```

How can I silence shouty if `missing_var` is sometimes not there?

Is there something like `{{ missing_var|ignore }}`?

Does this work:  `{{ missing_var|default:"" }}` ?

**Comment by kezabelle** [comment]
> Does this work: {{ missing_var|default:"" }} ?

I honestly can't recall how it interacts with filters like `{{ x|default:"" }}` or if I've even tested it (or how I even feel about which way it should work!).

> How can I silence shouty if missing_var is sometimes not there?

The only method by which it may definitively be silenced is via the project level setting, eg: for the example given, one of:
```
SHOUTY_VARIABLE_BLACKLIST = {
    'missing_var': ['*'],   # should ignore it everywhere
}
# OR
SHOUTY_VARIABLE_BLACKLIST = {
    'missing_var': ['my_app/my_template.html'],   # should ignore it for just that template + subtemplates
}
```
the reason for that is by design, if the variable is only *sometimes* present, your Context has broken the **contract** with the Template about the data (the template says needs `missing_var`) and it's only through Django's relaxed approach to silent variable failure that things just continue to work (sometimes erroneously).

Whenever you see a `MissingVariable` exception, the text should hopefully be guiding you towards how to silence that on a per project and/or per template basis using the above project level settings (i.e your `settings.py`), precisely because no project is perfect.

The downside of that is that it's a lot of manual copy-pasting template paths & refreshing. 
The upside is that once the page loads, you:
- know that the context is 'good'
- have a list of problematic variables/attributes stored in your settings (and thus git/hg/svn etc) which you can fix at some other point in the future.

**Comment by guettli** [comment]
thank you very much for the clarification.

**Comment by kezabelle** [comment]
No problem, thanks for dropping by.
If there's anything that could be made clearer in the "docs" (the readme/pypi description) that would've helped clarify things, please let me know and I'll consider incorporating.

**Comment by guettli** [comment]
Thank you for your feedback.

At the moment I will use pytest-django with this config:

```
[pytest]
FAIL_INVALID_TEMPLATE_VARS = True
```
See: https://pytest-django.readthedocs.io/en/latest/usage.html?highlight=invalid#additional-command-line-options

Maybe I will switch to django-shouty later.
